CREATE DATABASE listaContatos;

USE listaContatos;

CREATE TABLE usuario(
	id SMALLINT PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL UNIQUE,
    senha VARCHAR(30) NOT NULL
);

CREATE TABLE contato(
	id SMALLINT PRIMARY KEY AUTO_INCREMENT,
    nome VARCHAR(20) NOT NULL,
    endereco VARCHAR(100) NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(80) NOT NULL,
    idUsuario SMALLINT NOT NULL,
    FOREIGN KEY (idUsuario) REFERENCES usuario(id) 
);

